---
# let's ask the operator for the package name and whether
# or not we want to install or uninstall it (state = present|absent)

- name: install a package
  hosts: localhost
  vars_prompt:
    - name: package_name
      prompt: "Enter the package name"
      private: no
    - name: package_state
      prompt: "Enter the package state"
      private: no
  tasks:
    - name: install a package
      apt:
        pkg: "{{ package_name }}"
        state: "{{ package_state }}"
