# tasks can also be skipped (or not) with what we call "tags".
# depending on the tags we pass, some tasks will be run, others not
# be carefull with tags, it doesn't always work as you think it will.

# ansible-playbook -t set_fact -t install 08_conditions_with_tags.yaml
# ansible-playbook -t debug 08_conditions_with_tags.yaml
# ansible-playbook 8_conditions_with_tags.yaml

---
- name: a playbook with multiple tasks that run based on tags
  hosts: localhost
  vars_files:
  - vars/families.yaml
  tasks:
    - name: debug something
      debug:
        msg: Hello, world!
      tags:
        - debug
    - name: debug families
      debug:
        var: families
      tags:
        - debug
    - name: set package name and state with defaults
      set_fact:
        package_name: "{{ name | default('hello') }}"
        package_state: "{{ state | default('present') }}"
      tags:
        - set_fact
    - name: install a package
      apt:
        pkg: "{{ package_name }}"
        state: "{{ package_state }}"
      tags:
        - install

    - name: a task that always runs
      debug:
        msg: This task always runs
      tags:
        - always
