---
- name: example of several lookup plugins (set_fact and debug)
  hosts: localhost
  tasks:
  - name: set_fact with lookup
    set_fact:
      lipsum: "{{ lookup('file', 'files/lipsum.txt').split('\n') }}"

  - name: debug lipsum
    debug:
      var: lipsum

  - name: set_fact with lookup env home
    set_fact:
      home: "{{ lookup('env', 'HOME') }}"

  - name: debug home
    debug:
      var: home

  - name: get template
    set_fact:
      family_summary: "{{ lookup('template', 'templates/family_summary.j2') }}"

  - name: debug template output
    debug:
      var: family_summary
